# ----------------------------------------------------------------------- #
# ******************************* General ******************************* #
# ----------------------------------------------------------------------- #
ci:
  - .github/workflows/*

maintenance:
  - ./*
  - .github/*

documentation:
  - README.md
  - ./**/README*

# ----------------------------------------------------------------------- #
# ******************************* Project ******************************* #
# ----------------------------------------------------------------------- #

# Source Code
source-code:
  - src/**

# Tests
tests:
  - tests/**

# Dockerfile
docker:
  - Dockerfile
